algoritmo "Par ou Ímpar"
// Disciplina  : [Algoritmos e Lógica de Programação]
// Professor   : [Henrique Muller]
// Descrição   : Leia 1 (um) número inteiro e escreva se este número é par ou impar.
// Autor(a)    : Ademar Rafhael Oliveira Viana
// Data atual  : 17/09/2023
var

num1 : real 

inicio

escreva ("Número: ")
leia (num1)
escreval(num1)
escreval("------------------")

se (num1 % 2 = 0) entao
    escreval ("Par")
senao
    escreval ("Ímpar")
fimse

fimalgoritmo