algoritmo "Área de um Quadrado"
// Disciplina  : [Algoritmos e Lógica de Programação]
// Professor   : [Henrique Muller]
// Descrição   : O programa lê o valor do lado de um quadrado, calcula e escreve sua área.
// Autor(a)    : Ademar Rafhael Oliveira Viana
// Data atual  : 26/08/2023
var

area,lado : real

inicio

    escreva("Digite a medida do lado(cm): ")
        leia(lado)
        escreval(lado)

area <- lado ^ 2

escreva("Área do Quadrado: ",area," cm3")

fimalgoritmo
